import "../styles/global.css";
import Navbar from "../componetns/Navigation/Navbar";
import Footer from "../componetns/Footer/Footer";
import Head from "next/head";
import { ProductProvider } from "@/componetns/ProductCotext";
import { Inter, Roboto_Mono, Poppins } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight:["100","200"],
  variable: "--font-poppins",
  display: "swap",
});
// async function getData() {
//   const res = await fetch("https://kea-alt-del.dk/t7/api/products/1163");

//   // The return value is *not* serialized
//   // You can return Date, Map, Set, etc.

//   // Recommendation: handle errors
//   if (!res.ok) {
//     // This will activate the closest `error.js` Error Boundary
//     throw new Error("Failed to fetch data");
//   }
//   return res.json();
// }

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // Define a function to update the state

  // const product = await getData();

  return (
    <ProductProvider>
      <html lang="en" className={`${inter.variable} ${roboto_mono.variable} $ ${poppins.variable}`}>
        <body>
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </ProductProvider>
  );
}
